site_name: My Docs
site_url: https://stocks.luislogs.com
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: green
      accent: deep orange
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: green
      accent: deep purple
plugins:
  - blog:
      blog_dir: .
  - rss:
      match_path: posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
  ## Callouts
  - admonition
  - pymdownx.details
  - pymdownx.superfences